import React, { useMemo, useEffect } from 'react';
import { useMenuData } from '../features/dashboard/hooks/useMenuData';
import { generateDynamicRoutes } from '../utils/generateRoutes';
import { useRoutes } from 'react-router-dom';

const DynamicRoutesWrapper: React.FC = () => {
  const { menus, loading } = useMenuData();

  // ✅ Log what useMenuData returned
  useEffect(() => {
    console.log("🌀 useMenuData loading:", loading);
    console.log("📦 Menus from DB:", menus);
  }, [menus, loading]);

  const dynamicRoutes = useMemo(() => {
    const routes = loading ? [] : generateDynamicRoutes(menus);
    console.log("🧭 Routes generated by generateDynamicRoutes():", routes);

    routes.forEach(route => {
      console.log(`▶️ Parent Route: /${route.path}`);
      if (route.children?.length) {
        route.children.forEach(child => {
          console.log(`   └── /${route.path}/${child.path}`);
        });
      }
    });

    return routes;
  }, [menus, loading]);

  const element = useRoutes(dynamicRoutes);

  if (loading) {
    return <div className="text-center p-4">Loading routes...</div>;
  }

  return element ?? <div className="text-center text-danger">❌ No routes available</div>;
};

export default DynamicRoutesWrapper;
